version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    parallelism: 2
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: |
                echo "-"
                ALL_TESTS=$(circleci tests glob "test/*")
                TESTS_TO_RUN=$(echo $ALL_TESTS | circleci tests split)
                echo $TESTS_TO_RUN
                if [[ $TESTS_TO_RUN ]]
                then
                  TESTS_ARG='{'$(echo $ALL_TESTS | circleci tests split | tr ' ' ',')'}'
                  echo $TESTS_ARG
                  MOCHA_FILE=./test_results/mocha.xml npx mocha $TESTS_ARG --timeout 5000 --reporter mocha-junit-reporter
                fi
            - store_test_results:
                path: test_results
            - store_artifacts:
                path: test_results
workflows:
    build-and-test:
      jobs:
        - build-and-test
