version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    parallelism: 2
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: MOCHA_FILE=./test_results/mocha.xml npx mocha test --reporter mocha-junit-reporter
            - store_test_results:
                path: test_results
            - store_artifacts:
                path: test_results
workflows:
    build-and-test:
      jobs:
        - build-and-test
