version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    parallelism: 3
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: |
                echo "-"
                TESTS_TO_RUN=$(circleci tests glob $(pwd)"/test/*" | circleci tests split --split-by=timings --timings-type=testname)
                NUM_TESTS=$(echo $TESTS_TO_RUN | wc -w)
                echo $TESTS_TO_RUN
                if [[ $TESTS_TO_RUN ]]
                then
                  if (( $NUM_TESTS > 1 ))
                  then
                    TESTS_ARG='{'$(echo $TESTS_TO_RUN | tr ' ' ',')'}'
                  else
                    TEST_ARG=$TESTS_TO_RUN
                  fi
                  echo $TESTS_ARG
                  MOCHA_FILE=./test_results/mocha.xml npx mocha $TESTS_ARG --timeout 5000 --reporter mocha-junit-reporter
                fi
            - store_test_results:
                path: test_results
            - store_artifacts:
                path: test_results
            - store_artifacts:
                path: /.circleci-task-data/circle-test-results
workflows:
    build-and-test:
      jobs:
        - build-and-test
